//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTesting.WcfDestinationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfDestinationService.IWcfMessagingService")]
    public interface IWcfMessagingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMessagingService/InitializeProcess", ReplyAction="http://tempuri.org/IWcfMessagingService/InitializeProcessResponse")]
        bool InitializeProcess(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMessagingService/InitializeProcess", ReplyAction="http://tempuri.org/IWcfMessagingService/InitializeProcessResponse")]
        System.Threading.Tasks.Task<bool> InitializeProcessAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfMessagingServiceChannel : CodeTesting.WcfDestinationService.IWcfMessagingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfMessagingServiceClient : System.ServiceModel.ClientBase<CodeTesting.WcfDestinationService.IWcfMessagingService>, CodeTesting.WcfDestinationService.IWcfMessagingService {
        
        public WcfMessagingServiceClient() {
        }
        
        public WcfMessagingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfMessagingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfMessagingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfMessagingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InitializeProcess(string message) {
            return base.Channel.InitializeProcess(message);
        }
        
        public System.Threading.Tasks.Task<bool> InitializeProcessAsync(string message) {
            return base.Channel.InitializeProcessAsync(message);
        }
    }
}
