//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
using System;
using System.Collections.Generic;
using System.IO;
using System.Xml;
using System.Xml.Serialization;

namespace BC.Integration.Canonical.CanonicalReturn
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
  //  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://BC.Integration.Schema.ECommerce.SalesChannelOrder")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://BC.Integration.Schema.ECommerce.SalesChannelOrder", IsNullable = false)]
    public partial class Return
    {

        private string processField;

        private ReturnHeader headerField;

        private List<ReturnLine> returnLineItems;

        private List<ReturnAddress> addressesField;

        private List<ReturnDiscounts> discountsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Process
        {
            get
            {
                return this.processField;
            }
            set
            {
                this.processField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReturnHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LineItem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<ReturnLine> ReturnLineItems
        {
            get
            {
                return this.returnLineItems;
            }
            set
            {
                this.returnLineItems = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Address", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<ReturnAddress> Addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Discount", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<ReturnDiscounts> Discounts
        {
            get
            {
                return this.discountsField;
            }
            set
            {
                this.discountsField = value;
            }
        }

        /// <summary>
        /// This method serializes an object model to an xml string.
        /// </summary>
        /// <param name="doc">The invoice document object to be serialized</param>
        /// <returns>XML string representation of the invoice document</returns>
        public string ConvertReturnToString()
        {
            StringWriter sw = new StringWriter();
            XmlTextWriter tw = null;
            try
            {
                XmlSerializer serializer = new XmlSerializer(this.GetType());
                tw = new XmlTextWriter(sw);
                serializer.Serialize(tw, this);
            }
            catch (Exception ex)
            {
                throw new Exception("Error occured serializing the BC.Integration.Canonical.CanonicalReturn Document object model.  The error occured in the ConvertReturnToString method.", ex);
            }
            finally
            {
                sw.Close();
                if (tw != null)
                {
                    tw.Close();
                }
            }
            return sw.ToString();
        }

        /// <summary>
        /// This method is used to deserialize a XML representation of a product to the object model.
        /// </summary>
        /// <param name="doc"></param>
        /// <returns></returns>
        public Return ConvertToObjectModel(string doc)
        {
            using (TextReader sr = new StringReader(doc))
            {
                var serializer = new System.Xml.Serialization.XmlSerializer(typeof(Return));
                Return obj = (Return)serializer.Deserialize(sr);
                return obj;
            }

        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://BC.Integration.Schema.ECommerce.SalesChannelOrder")]
    public partial class ReturnHeader
    {

        private string orderNumberField;

        private int siteIdField;

        private string currencyIdField;

        private string taxRegistrationNumberField;

        private string carrierCodeField;

        private string paymentTypeField;

        private string customerIdField;

        private string customerPONumField;

        //private string shipAddIdField;

        //private string shipCustNameField;

        //private string shipCustAdd1Field;

        //private string shipCustAdd2Field;

        //private string shipCustAdd3Field;

        //private string shipCityField;

        //private string shipPostalCodeField;

        //private string shipCountryField;

        //private string shipPhoneField;

        //private string billAddIdField;

        //private string billCustNameField;

        //private string billCustAdd1Field;

        //private string billCustAdd2Field;

        //private string billCustAdd3Field;

        //private string billCityField;

        //private string billPostalCodeField;

        //private string billCountryField;

        //private string billPhoneField;

        private string custEmailField;

        private System.DateTime orderDateField;

        private System.DateTime quoteExpirationDateField;

        private System.DateTime cancelDateField;

        private System.DateTime reqShipDateField;

        private string paymentMethodField;

        private string commentField;

        private string incoTermsField;

        private decimal discountField;

        private string priceCodeField;

        private decimal freightField;

        private decimal taxAmountField;

        private bool isStaffOrderField;

        private bool itHasGiftCardField;

        private bool itHasDiscountField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int SiteId
        {
            get
            {
                return this.siteIdField;
            }
            set
            {
                this.siteIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrencyId
        {
            get
            {
                return this.currencyIdField;
            }
            set
            {
                this.currencyIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TaxRegistrationNumber
        {
            get
            {
                return this.taxRegistrationNumberField;
            }
            set
            {
                this.taxRegistrationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CarrierCode
        {
            get
            {
                return this.carrierCodeField;
            }
            set
            {
                this.carrierCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PaymentType
        {
            get
            {
                return this.paymentTypeField;
            }
            set
            {
                this.paymentTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerPONum
        {
            get
            {
                return this.customerPONumField;
            }
            set
            {
                this.customerPONumField = value;
            }
        }

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string ShipAddId
        //{
        //    get
        //    {
        //        return this.shipAddIdField;
        //    }
        //    set
        //    {
        //        this.shipAddIdField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string ShipCustName
        //{
        //    get
        //    {
        //        return this.shipCustNameField;
        //    }
        //    set
        //    {
        //        this.shipCustNameField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string ShipCustAdd1
        //{
        //    get
        //    {
        //        return this.shipCustAdd1Field;
        //    }
        //    set
        //    {
        //        this.shipCustAdd1Field = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string ShipCustAdd2
        //{
        //    get
        //    {
        //        return this.shipCustAdd2Field;
        //    }
        //    set
        //    {
        //        this.shipCustAdd2Field = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string ShipCustAdd3
        //{
        //    get
        //    {
        //        return this.shipCustAdd3Field;
        //    }
        //    set
        //    {
        //        this.shipCustAdd3Field = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string ShipCity
        //{
        //    get
        //    {
        //        return this.shipCityField;
        //    }
        //    set
        //    {
        //        this.shipCityField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string ShipPostalCode
        //{
        //    get
        //    {
        //        return this.shipPostalCodeField;
        //    }
        //    set
        //    {
        //        this.shipPostalCodeField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string ShipCountry
        //{
        //    get
        //    {
        //        return this.shipCountryField;
        //    }
        //    set
        //    {
        //        this.shipCountryField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string ShipPhone
        //{
        //    get
        //    {
        //        return this.shipPhoneField;
        //    }
        //    set
        //    {
        //        this.shipPhoneField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string BillAddId
        //{
        //    get
        //    {
        //        return this.billAddIdField;
        //    }
        //    set
        //    {
        //        this.billAddIdField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string BillCustName
        //{
        //    get
        //    {
        //        return this.billCustNameField;
        //    }
        //    set
        //    {
        //        this.billCustNameField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string BillCustAdd1
        //{
        //    get
        //    {
        //        return this.billCustAdd1Field;
        //    }
        //    set
        //    {
        //        this.billCustAdd1Field = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string BillCustAdd2
        //{
        //    get
        //    {
        //        return this.billCustAdd2Field;
        //    }
        //    set
        //    {
        //        this.billCustAdd2Field = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string BillCustAdd3
        //{
        //    get
        //    {
        //        return this.billCustAdd3Field;
        //    }
        //    set
        //    {
        //        this.billCustAdd3Field = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string BillCity
        //{
        //    get
        //    {
        //        return this.billCityField;
        //    }
        //    set
        //    {
        //        this.billCityField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string BillPostalCode
        //{
        //    get
        //    {
        //        return this.billPostalCodeField;
        //    }
        //    set
        //    {
        //        this.billPostalCodeField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string BillCountry
        //{
        //    get
        //    {
        //        return this.billCountryField;
        //    }
        //    set
        //    {
        //        this.billCountryField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public string BillPhone
        //{
        //    get
        //    {
        //        return this.billPhoneField;
        //    }
        //    set
        //    {
        //        this.billPhoneField = value;
        //    }
        //}

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustEmail
        {
            get
            {
                return this.custEmailField;
            }
            set
            {
                this.custEmailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime QuoteExpirationDate
        {
            get
            {
                return this.quoteExpirationDateField;
            }
            set
            {
                this.quoteExpirationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime CancelDate
        {
            get
            {
                return this.cancelDateField;
            }
            set
            {
                this.cancelDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime ReqShipDate
        {
            get
            {
                return this.reqShipDateField;
            }
            set
            {
                this.reqShipDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PaymentMethod
        {
            get
            {
                return this.paymentMethodField;
            }
            set
            {
                this.paymentMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IncoTerms
        {
            get
            {
                return this.incoTermsField;
            }
            set
            {
                this.incoTermsField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PriceCode
        {
            get
            {
                return this.priceCodeField;
            }
            set
            {
                this.priceCodeField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Freight
        {
            get
            {
                return this.freightField;
            }
            set
            {
                this.freightField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TaxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isStaffOrder
        {
            get
            {
                return this.isStaffOrderField;
            }
            set
            {
                this.isStaffOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool itHasGiftCard
        {
            get
            {
                return this.itHasGiftCardField;
            }
            set
            {
                this.itHasGiftCardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool itHasDiscount
        {
            get
            {
                return this.itHasDiscountField;
            }
            set
            {
                this.itHasDiscountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://BC.Integration.Schema.ECommerce.SalesChannelOrder")]
    public partial class ReturnLine
    {
        private string returnId;
        private DateTime createdDate;
        private string createdBy;
        private string rmaCode;
        private string returnStatus;
        private string returnType;
        private string physicalReturn;
        private string exchangeOrderId;
        private decimal shippingCost;
        private decimal shippingDiscount;
        private decimal lessRestockAmount;

        private string receivedBy;
        private List<ReturnSKU> SKUList;


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnId
        {
            get
            {
                return this.returnId;
            }
            set
            {
                this.returnId = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public DateTime CreatedDate
        {
            get
            {
                return this.createdDate;
            }
            set
            {
                this.createdDate = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreatedBy
        {
            get
            {
                return this.createdBy;
            }
            set
            {
                this.createdBy = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RmaCode
        {
            get
            {
                return this.rmaCode;
            }
            set
            {
                this.rmaCode = value;
            }
        }

 
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnStatus
        {
            get
            {
                return this.returnStatus;
            }
            set
            {
                this.returnStatus = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnType
        {
            get
            {
                return this.returnType;
            }
            set
            {
                this.returnType = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsPhysicalReturn
        {
            get
            {
                return this.physicalReturn;
            }
            set
            {
                this.physicalReturn = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public string ExchangeOrderId
        {
            get
            {
                return this.exchangeOrderId;
            }
            set
            {
                this.exchangeOrderId = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ShippingCost
        {
            get
            {
                return this.shippingCost;
            }
            set
            {
                this.shippingCost = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LessRestockAmount
        {
            get
            {
                return this.lessRestockAmount;
            }
            set
            {
                this.lessRestockAmount = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceivedBy
        {
            get
            {
                return this.receivedBy;
            }
            set
            {
                this.receivedBy = value;
            }
        }

 
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ShippingDiscount
        {
            get
            {
                return this.shippingDiscount;
            }
            set
            {
                this.shippingDiscount = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<ReturnSKU> SKU
        {
            get
            {
                return this.SKUList;
            }
            set
            {
                this.SKUList = value;
            }
        }

        public void AddSku(ReturnSKU sku)
        {
            this.SKUList.Add(sku);
        }
    }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://BC.Integration.Schema.ECommerce.SalesChannelOrder")]
    public partial class ReturnSKU
    {
        private string returnSKUId;
        private string returnItemCode;
        private string lineItemId;
        private int quantity;
        private int receivedQuantity;
        private decimal returnAmount;
        private decimal unitPrice;
        private decimal tax;
        private decimal itemSubtotalPrice;
        private decimal amountBeforeTax;
        private decimal amountIncludingTax;


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnSKUId
        {
            get
            {
                return this.returnSKUId;
            }
            set
            {
                this.returnSKUId = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnItemCode
        {
            get
            {
                return this.returnItemCode;
            }
            set
            {
                this.returnItemCode = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineItemId
        {
            get
            {
                return this.lineItemId;
            }
            set
            {
                this.lineItemId = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Quantity
        {
            get
            {
                return this.quantity;
            }
            set
            {
                this.quantity = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ReceivedQuantity
        {
            get
            {
                return this.receivedQuantity;
            }
            set
            {
                this.receivedQuantity = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ReturnAmount
        {
            get
            {
                return this.returnAmount;
            }
            set
            {
                this.returnAmount = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal UnitPrice
        {
            get
            {
                return this.unitPrice;
            }
            set
            {
                this.unitPrice = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public decimal Tax
        {
            get
            {
                return this.tax;
            }
            set
            {
                this.tax = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ItemSubtotalPrice
        {
            get
            {
                return this.itemSubtotalPrice;
            }
            set
            {
                this.itemSubtotalPrice = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AmountBeforeTax
        {
            get
            {
                return this.amountBeforeTax;
            }
            set
            {
                this.amountBeforeTax = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AmountInludingTax
        {
            get
            {
                return this.amountIncludingTax;
            }
            set
            {
                this.amountIncludingTax = value;
            }
        }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://BC.Integration.Schema.ECommerce.SalesChannelOrder")]
    public partial class ReturnAddress
    {

        private string addressIdField;

        private string customerNameField;

        private string add1Field;

        private string add2Field;

        private string add3Field;

        private string addCityField;

        private string addPostalCodeField;

        private string countryField;

        private string phoneField;

        private string emailField;

        private string addressType;

        private string stateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressId
        {
            get
            {
                return this.addressIdField;
            }
            set
            {
                this.addressIdField = value;
            }
        }
        public ReturnAddress DeepCopy()
        {
            ReturnAddress other = (ReturnAddress)this.MemberwiseClone();
            other.addressIdField = addressIdField;
            other.customerNameField = customerNameField;
            other.add1Field = add1Field;
            other.add2Field = add2Field;
            other.add3Field = add3Field;
            other.addCityField = addCityField;
            other.addPostalCodeField = addPostalCodeField;
            other.countryField = countryField;
            other.phoneField = phoneField;
            other.emailField = emailField;
            other.addressType = addressType;
            other.stateField = stateField;

            return other;
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Add1
        {
            get
            {
                return this.add1Field;
            }
            set
            {
                this.add1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Add2
        {
            get
            {
                return this.add2Field;
            }
            set
            {
                this.add2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Add3
        {
            get
            {
                return this.add3Field;
            }
            set
            {
                this.add3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddCity
        {
            get
            {
                return this.addCityField;
            }
            set
            {
                this.addCityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddPostalCode
        {
            get
            {
                return this.addPostalCodeField;
            }
            set
            {
                this.addPostalCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressType
        {
            get
            {
                return this.addressType;
            }
            set
            {
                this.addressType = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://BC.Integration.Schema.ECommerce.SalesChannelOrder")]
    public partial class ReturnDiscounts
    {
        private string discountCodeField;
        private string discountItemNumberField;
        private string displayNameField;


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DiscountCode
        {
            get
            {
                return this.discountCodeField;
            }
            set
            {
                this.discountCodeField = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DiscountItemNumber
        {
            get
            {
                return this.discountItemNumberField;
            }
            set
            {
                this.discountItemNumberField = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }
    }
}
