//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqsQueueTester.SalesWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesWebService.IWebSvc")]
    public interface IWebSvc {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWebSvc/InitializeProcess")]
        void InitializeProcess(string guid);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWebSvc/InitializeProcess")]
        System.Threading.Tasks.Task InitializeProcessAsync(string guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebSvcChannel : SqsQueueTester.SalesWebService.IWebSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebSvcClient : System.ServiceModel.ClientBase<SqsQueueTester.SalesWebService.IWebSvc>, SqsQueueTester.SalesWebService.IWebSvc {
        
        public WebSvcClient() {
        }
        
        public WebSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InitializeProcess(string guid) {
            base.Channel.InitializeProcess(guid);
        }
        
        public System.Threading.Tasks.Task InitializeProcessAsync(string guid) {
            return base.Channel.InitializeProcessAsync(guid);
        }
    }
}
