//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BC.Integration.Utility.PushService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PushService.IPushSvc")]
    public interface IPushSvc {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPushSvc/InitializeProcess")]
        void InitializeProcess(string guid, string queueName, decimal maxRate, bool isBatch, int maxBatchSize);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPushSvc/InitializeProcess")]
        System.Threading.Tasks.Task InitializeProcessAsync(string guid, string queueName, decimal maxRate, bool isBatch, int maxBatchSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPushSvcChannel : BC.Integration.Utility.PushService.IPushSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PushSvcClient : System.ServiceModel.ClientBase<BC.Integration.Utility.PushService.IPushSvc>, BC.Integration.Utility.PushService.IPushSvc {
        
        public PushSvcClient() {
        }
        
        public PushSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PushSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InitializeProcess(string guid, string queueName, decimal maxRate, bool isBatch, int maxBatchSize) {
            base.Channel.InitializeProcess(guid, queueName, maxRate, isBatch, maxBatchSize);
        }
        
        public System.Threading.Tasks.Task InitializeProcessAsync(string guid, string queueName, decimal maxRate, bool isBatch, int maxBatchSize) {
            return base.Channel.InitializeProcessAsync(guid, queueName, maxRate, isBatch, maxBatchSize);
        }
    }
}
