//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Integration.Utility.OnRampService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OnRampService.IOnRampSvc")]
    public interface IOnRampSvc {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOnRampSvc/InitializeProcess")]
        void InitializeProcess(string guid);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOnRampSvc/InitializeProcess")]
        System.Threading.Tasks.Task InitializeProcessAsync(string guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOnRampSvcChannel : Corp.Integration.Utility.OnRampService.IOnRampSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnRampSvcClient : System.ServiceModel.ClientBase<Corp.Integration.Utility.OnRampService.IOnRampSvc>, Corp.Integration.Utility.OnRampService.IOnRampSvc {
        
        public OnRampSvcClient() {
        }
        
        public OnRampSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnRampSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnRampSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnRampSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InitializeProcess(string guid) {
            base.Channel.InitializeProcess(guid);
        }
        
        public System.Threading.Tasks.Task InitializeProcessAsync(string guid) {
            return base.Channel.InitializeProcessAsync(guid);
        }
    }
}
