using System.Xml.Serialization;
using System.IO;
using System.Xml;
using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Corp.Integration.Canonical
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Corp.Integration.Canonical.InventoryTransfer")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://Corp.Integration.Canonical.InventoryTransfer", IsNullable = false)]
    public partial class InventoryTransferRequest
    {

        private InventoryTransferRequestHeader headerField;

        private InventoryTransferRequestItem[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventoryTransferRequestHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public InventoryTransferRequestItem[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <summary>
        /// This method serializes an object model to an xml string.
        /// </summary>
        /// <param name="doc">The Inventory Transfer Request document object to be serialized</param>
        /// <returns>XML string representation of the Inventory Transfer Request document</returns>
        public string ConvertToString(InventoryTransferRequest doc)
        {
            StringWriter sw = new StringWriter();
            XmlTextWriter tw = null;
            try
            {
                XmlSerializer serializer = new XmlSerializer(doc.GetType());
                tw = new XmlTextWriter(sw);
                serializer.Serialize(tw, doc);
            }
            catch (Exception ex)
            {
                throw new Exception("Error occured serializing the Corp.Integration.Canonical.InventoryTransferRequest Document object model.  The error occured in the ConvertToString method.", ex);
            }
            finally
            {
                sw.Close();
                if (tw != null)
                {
                    tw.Close();
                }
            }
            return sw.ToString();
        }

        /// <summary>
        /// This method is used to deserialize a XML representation of a Inventory Transfer Request to the object model.
        /// </summary>
        /// <param name="doc"></param>
        /// <returns></returns>
        public InventoryTransferRequest ConvertToObjectModel(string doc)
        {
            using (TextReader sr = new StringReader(doc))
            {
                var serializer = new System.Xml.Serialization.XmlSerializer(typeof(InventoryTransferRequest));
                InventoryTransferRequest msgEnv = (InventoryTransferRequest)serializer.Deserialize(sr);
                return msgEnv;
            }

        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Corp.Integration.Canonical.InventoryTransfer")]
    public partial class InventoryTransferRequestHeader
    {

        private string requestIdField;

        private System.DateTime requestTimestampField;

        private string receivingSiteIdField;

        private string receivingSiteNameField;

        private string sendingSiteIdField;

        private System.DateTime deliveryByTimestampField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime RequestTimestamp
        {
            get
            {
                return this.requestTimestampField;
            }
            set
            {
                this.requestTimestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceivingSiteId
        {
            get
            {
                return this.receivingSiteIdField;
            }
            set
            {
                this.receivingSiteIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceivingSiteName
        {
            get
            {
                return this.receivingSiteNameField;
            }
            set
            {
                this.receivingSiteNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SendingSiteId
        {
            get
            {
                return this.sendingSiteIdField;
            }
            set
            {
                this.sendingSiteIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DeliveryByTimestamp
        {
            get
            {
                return this.deliveryByTimestampField;
            }
            set
            {
                this.deliveryByTimestampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Corp.Integration.Canonical.InventoryTransfer")]
    public partial class InventoryTransferRequestItem
    {

        private string itemNumberField;

        private string quantityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber
        {
            get
            {
                return this.itemNumberField;
            }
            set
            {
                this.itemNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
    }
}
