//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTesting.SalesDocWcfSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesDocWcfSvc.ISalesDocWcfService")]
    public interface ISalesDocWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesDocWcfService/InitializeProcess", ReplyAction="http://tempuri.org/ISalesDocWcfService/InitializeProcessResponse")]
        bool InitializeProcess(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesDocWcfService/InitializeProcess", ReplyAction="http://tempuri.org/ISalesDocWcfService/InitializeProcessResponse")]
        System.Threading.Tasks.Task<bool> InitializeProcessAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesDocWcfServiceChannel : CodeTesting.SalesDocWcfSvc.ISalesDocWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesDocWcfServiceClient : System.ServiceModel.ClientBase<CodeTesting.SalesDocWcfSvc.ISalesDocWcfService>, CodeTesting.SalesDocWcfSvc.ISalesDocWcfService {
        
        public SalesDocWcfServiceClient() {
        }
        
        public SalesDocWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesDocWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesDocWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesDocWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InitializeProcess(string message) {
            return base.Channel.InitializeProcess(message);
        }
        
        public System.Threading.Tasks.Task<bool> InitializeProcessAsync(string message) {
            return base.Channel.InitializeProcessAsync(message);
        }
    }
}
