//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqsQueueTester.HeartBeat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HeartBeat.IHeartBeat")]
    public interface IHeartBeat {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeartBeat/Pulse", ReplyAction="http://tempuri.org/IHeartBeat/PulseResponse")]
        bool Pulse();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeartBeat/Pulse", ReplyAction="http://tempuri.org/IHeartBeat/PulseResponse")]
        System.Threading.Tasks.Task<bool> PulseAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeartBeatChannel : SqsQueueTester.HeartBeat.IHeartBeat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeartBeatClient : System.ServiceModel.ClientBase<SqsQueueTester.HeartBeat.IHeartBeat>, SqsQueueTester.HeartBeat.IHeartBeat {
        
        public HeartBeatClient() {
        }
        
        public HeartBeatClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HeartBeatClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeartBeatClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeartBeatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Pulse() {
            return base.Channel.Pulse();
        }
        
        public System.Threading.Tasks.Task<bool> PulseAsync() {
            return base.Channel.PulseAsync();
        }
    }
}
